language: java

jdk:
  - openjdk14

env:
  global:
    - CODECOV_TOKEN="2b702bbb-59e1-4a2e-a6c9-5e19f753d06a"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - anatoliy.gromov.service@gmail.com
    on_success: never
    on_failure: always